image: alpine/git:latest

pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        clone:
          enabled: false
        script:
          - git clone --mirror https://x-token-auth:"$BITBUCKET_VARIABLE"@bitbucket.org/fazeal/dataload-service.git
          - cd dataload-service.git
          - git push --mirror https://x-token-auth:"$GITHUB_VARIABLE"@github.com/Khasaleh/dataload-service.git
        test: false
